version: "${DOCKER_COMPOSE_VERSION}"
   
services:
  db:
    env_file: ./homie/.env
    image: postgres
    ports:
      - "${DB_PORT}:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "${WEBSERVER_PORT}:8000"
    depends_on:
      - db
